apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chatbot
  name: app-role
rules:
- apiGroups: 
    - ""
    - apps
    - batch
    - extensions
    - policy
    - rbac.authorization.k8s.io/v1
  resources:
    - pods
    - secrets
    - componentstatuses
    - configmaps
    - daemonsets
    - deployments
    - events
    - endpoints
    - horizontalpodautoscalers
    - ingress
    - jobs
    - limitranges
    - namespaces
    - nodes
    - pods
    - persistentvolumes
    - persistentvolumeclaims
    - resourcequotas
    - replicasets
    - replicationcontrollers
    - serviceaccounts
    - services
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]
