pipeline{
    parameters{
       choice (name:'terraformActions' , choice: ['apply','destroy'], description: 'choose your terraform action')
    }
    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')

    }
    agent any
    stages{
        stage('Checkout'){
            steps{
                dir("terraform"){
                    git url: 'https://github.com/Rohitdevops73/Rohit_Chatbot.git' , branch: 'IAC-devenv'
                    // }    
                }     
            }
        }
        stage('Plan'){
            steps{
                sh 'pwd; cd eks/; terraform init'
                sh 'pwd; cd eks/; terraform plan -out tfplan'
                sh 'pwd; cd eks/; terraform show -no-colour tfplan > tfplan.txt'
            }
        }
        stage('Approval'){
            steps{
                script{
                    def plan = readFile 'eks/tfplan.txt'
                    input message: "Do you want to proceed with terraform actions..?"
                    parameters: [text(name: 'Plan',description: 'Please review your plan',defaultValue: plan)]
                }
            }
        }
        stage('Apply/Destroy'){
            when {
                expression {
                    return params.terraformActions == 'apply' || params.terraformActions == 'destroy'
                }
            }
            steps{
                script{
                    if (params.terraformActions == 'apply'){
                        sh 'pwd; cd eks/; terraform apply -input=false tfplan'
                    }
                    else if (params.terraformActions == 'destroy'){
                        sh 'pwd; cd eks/; terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
}

